### ISSUE TITLE
Can it generate an architecture from search space without defining a fixed network?

### ISSUE THREAD

**Issue by freeman-1995** [negrinho/deep_architect#3]
Hi~ it's a nice work! However, according to document, I find the search space is a super-net, you have already define the connection between each modules or blocks. I just curious whether the framework can generate a architecture without prior knowledge about architecture structure?  I just want to get modules from search space and automatically connect them together.

**Comment by negrinho** [comment]
The short answer is: you have to have some set of possible connectivity patterns in mind and encode those (typically with a substitution module). An arbitrary set of modules can then rely on this substitution module (everything is pretty modular). 

You can encode choices between different connectivity patterns with substitution modules (e.g., see [`siso_permutation`](https://github.com/negrinho/deep_architect/blob/master/deep_architect/modules.py#L491). The exact substitution module depends on the possible connectivity patterns that you are looking for. If you can provide a concrete textual description of the search space that you are looking for, maybe I can help encode it.

The simplest case would be simply sequential choosing between a single-input single output-module at each position.  

``` python
import deep_architect.modules as mo 
import deep_architect.core as co
import deep_architect.hyperparameters as hp

# used to define dummy modules (for illustration purposes)
def module(name, name_to_hyperp):
    m = co.Module(name=name)
    m._register(['in'], ['out'], name_to_hyperp)
    return m.get_io()

def search_space():
    # replace this with desired modules.
    fns = [
           lambda: module("A", {'h' : hp.Discrete([0, 1])}),
           lambda: module("B", {'x' : hp.Discrete([64, 128, 256])}),
    ]
    fn = lambda: mo.siso_or(fns, hp.Discrete(list(range(len(fns)))))
    return mo.siso_repeat(fn, hp.Discrete([1, 2, 4, 8, 16]))

from deep_architect.searchers.common import random_specify
search_space_fn = mo.SearchSpaceFactory(search_space).get_search_space
inputs, outputs = search_space_fn()
vs = random_specify(outputs)
import deep_architect.visualization as vi
# vi.draw_graph(outputs)
inputs, outputs = search_space_fn()
vi.draw_graph_evolution(outputs, vs, '.')
```

[Here](https://github.com/negrinho/deep_architect/files/3907954/graph_evo.pdf) is the transition process for an example model drawn from the search space.

As a side note, I've changed a few things in this [branch](https://github.com/negrinho/deep_architect/tree/refactor_modules). It is nothing major, but it in the long run may make using modules more natural (less boilerplate). I haven't merged back into master because I haven't changed the documentation accordingly yet. Examples [here](https://github.com/negrinho/deep_architect/tree/refactor_modules/examples).

**Comment by freeman-1995** [comment]
Get it !  siso_permutation is Good for me, thx

**Comment by negrinho** [comment]
Great.  You need to pass an hyperparameter [`OneOfKFactorial`](https://github.com/negrinho/deep_architect/blob/master/deep_architect/hyperparameters.py#L99) to choose between permutations. Just a side note, `siso_permutation` is implemented rather naively right now (performance wise). Nonetheless, you shouldn't run into trouble for less than 10 elements. This can be improved easily but I haven't got around it yet.
